rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode

gemfile:
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: jruby-18mode
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: rbx-18mode
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
